apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nestjsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: nestjsapi
          image: yirengoo/nestjsapi:v2
          ports:
            - containerPort: 5000
